In [1]:
# Feature selection 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler

# Data management
import pandas as pd
import numpy as np

print('Imports complete.')

Imports complete.


In [2]:
# Import the data
path = '/media/notclaytonjohnson/Seagate Portable Drive/Data/urls_dataset/'
fille = 'All.csv'
df = pd.read_csv(path + fille)

print('Data read:')
print(df.head())

Data read:
   Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...  

In [3]:
dep_var = 'URL_Type_obf_Type'

print('There are {} columns and {} rows in the provided data.'.format(len(df.columns), len(df)))

There are 80 columns and 36707 rows in the provided data.


In [4]:
print('Below is the dataset\'s composition')
print(df[dep_var].value_counts())

Below is the dataset's composition
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: URL_Type_obf_Type, dtype: int64


In [5]:
# Removes all rows if they contain NaN values
df.dropna(axis='index', inplace=True)

In [6]:
print('There are {} columns and {} rows in the provided data.'.format(len(df.columns), len(df)))

print('Below is the dataset\'s composition')
print(df[dep_var].value_counts())

There are 80 columns and 18982 rows in the provided data.
Below is the dataset's composition
spam          5342
malware       4440
phishing      4014
benign        2709
Defacement    2477
Name: URL_Type_obf_Type, dtype: int64


In [7]:
# Create the X (data) and y (labels)
#X = pd.DataFrame( normalize(df.loc[:, df.columns != dep_var]), columns=df.columns[:-1] )

scaler = MinMaxScaler()
X = pd.DataFrame( scaler.fit_transform(df.loc[:, df.columns != dep_var]), columns=df.columns[:-1] )

y = df[dep_var]

In [8]:
print(X.head())

   Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0     0.000000            0.153846           0.00000           0.177083   
1     0.015884            0.153846           0.09375           0.177083   
2     0.016606            0.153846           0.09375           0.177083   
3     0.015884            0.153846           0.09375           0.177083   
4     0.016606            0.153846           0.09375           0.177083   

   longdomaintokenlen  avgpathtokenlen       tld  charcompvowels  charcompace  \
0            0.245902         0.083969  0.153846        0.020725     0.014085   
1            0.245902         0.076336  0.153846        0.098446     0.070423   
2            0.245902         0.076336  0.153846        0.098446     0.070423   
3            0.245902         0.076336  0.153846        0.098446     0.070423   
4            0.245902         0.076336  0.153846        0.098446     0.070423   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileNa

In [9]:
print(y.head())

35    Defacement
37    Defacement
38    Defacement
39    Defacement
40    Defacement
Name: URL_Type_obf_Type, dtype: object


In [10]:
# Begin the feature selection process using the SelectKBest object from scikit-learn
X_new = SelectKBest(chi2, k=10).fit_transform(X, y)

In [11]:
print(X_new)

[[0.         0.         0.03871459 ... 0.         0.         0.        ]
 [0.         0.         0.4821902  ... 0.         0.54255319 0.87458339]
 [0.         0.         0.48757384 ... 0.         0.55208333 0.87413385]
 ...
 [0.08695652 0.38709677 0.75902627 ... 0.         0.51470588 0.85262228]
 [0.03381643 0.12903226 0.62794394 ... 0.         0.70909091 0.89538585]
 [0.0821256  0.19354839 0.74120529 ... 0.         0.53       0.88461893]]


## Multi-class Feature Analysis

In [12]:
"""print('The data presented in this block is bad statistics!')

select = SelectKBest(chi2, k='all')
fit = select.fit(X, y)

dictt = []
i=0
removed_columns = []
for col in X.columns:
    score = fit.scores_[i]
    #print(score)
    i+=1
    if not np.isnan(float(score)):
        dictt.append([col, score])    
    else:
        removed_columns.append(col)
#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)
dictt.sort(key=lambda arr : float(arr[1]), reverse=True)

outstr = ''
i=1
for col, score in dictt:
    #if not math.isnan(float(score)):
    print('{}\t{}\t{}'.format(i, col, score))
    i+=1
    outstr += '\'' + col + '\', '

if len(removed_columns) > 0:
    print('Removed columns: {}'.format(removed_columns))
print('Columns in order from best to worst: {}'.format(outstr[:-2]))

print('The data presented in this block is bad statistics!')"""

"print('The data presented in this block is bad statistics!')\n\nselect = SelectKBest(chi2, k='all')\nfit = select.fit(X, y)\n\ndictt = []\ni=0\nremoved_columns = []\nfor col in X.columns:\n    score = fit.scores_[i]\n    #print(score)\n    i+=1\n    if not np.isnan(float(score)):\n        dictt.append([col, score])    \n    else:\n        removed_columns.append(col)\n#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)\ndictt.sort(key=lambda arr : float(arr[1]), reverse=True)\n\noutstr = ''\ni=1\nfor col, score in dictt:\n    #if not math.isnan(float(score)):\n    print('{}\t{}\t{}'.format(i, col, score))\n    i+=1\n    outstr += ''' + col + '', '\n\nif len(removed_columns) > 0:\n    print('Removed columns: {}'.format(removed_columns))\nprint('Columns in order from best to worst: {}'.format(outstr[:-2]))\n\nprint('The data presented in this block is bad statistics!')"

In [13]:
# Additions of another work found here: https://towardsdatascience.com/chi-square-test-for-feature-selection-in-machine-learning-206b1f0b8223
chi_scores = chi2(X, y)
p_values = pd.Series(chi_scores[1],index = X.columns)
p_values.sort_values(ascending = False , inplace = True)
#p_values.plot.bar()
print('Values in order of descending p-values (higher=more significant)')
print(p_values.index)

Values in order of descending p-values (higher=more significant)
Index(['Entropy_URL', 'Path_LongestWordLength', 'dld_domain',
       'sub-Directory_LongestWordLength', 'isPortEighty', 'avgpathtokenlen',
       'host_letter_count', 'Entropy_Domain', 'domainlength', 'ldl_domain',
       'longdomaintokenlen', 'URL_sensitiveWord', 'Directory_LetterCount',
       'Directory_DigitCount', 'NumberofDotsinURL', 'Domain_LongestWordLength',
       'delimeter_Domain', 'NumberRate_DirectoryName', 'File_name_DigitCount',
       'path_token_count', 'avgdomaintokenlen', 'SymbolCount_Directoryname',
       'ldl_filename', 'dld_filename', 'Entropy_Extension',
       'Filename_LetterCount', 'pathurlRatio', 'executable', 'spcharUrl',
       'CharacterContinuityRate', 'charcompvowels',
       'Arguments_LongestWordLength', 'delimeter_path',
       'Entropy_DirectoryName', 'Entropy_Filename', 'SymbolCount_URL',
       'NumberRate_FileName', 'NumberRate_Extension', 'domainUrlRatio',
       'SymbolCount_File

In [14]:
p_values.head(10)

Entropy_URL                        1.272731e-01
Path_LongestWordLength             1.380409e-02
dld_domain                         4.124519e-04
sub-Directory_LongestWordLength    3.440676e-04
isPortEighty                       2.881362e-05
avgpathtokenlen                    1.192005e-07
host_letter_count                  1.007751e-08
Entropy_Domain                     6.009946e-09
domainlength                       8.353102e-10
ldl_domain                         7.808014e-11
dtype: float64

In [15]:
p_values.tail(11)

LongestVariableValue       2.788998e-135
Query_DigitCount           1.118545e-135
ldl_getArg                 1.714726e-147
dld_getArg                 1.534782e-147
Extension_DigitCount       6.874504e-171
ArgUrlRatio                3.924478e-272
NumberRate_Domain          5.645027e-279
NumberRate_AfterPath       1.983143e-290
argPathRatio               1.397820e-290
Entropy_Afterpath           0.000000e+00
ISIpAddressInDomainName              NaN
dtype: float64

## Binary Class Feature Analysis

In [16]:
y = y.map(lambda label : label if label == 'benign' else 'malicious')
print(y.value_counts())

malicious    16273
benign        2709
Name: URL_Type_obf_Type, dtype: int64


In [17]:
"""print('The data presented in this block is bad statistics!')

select = SelectKBest(chi2, k='all')
fit = select.fit(X, y)

dictt = []
i=0
removed_columns = []
for col in X.columns:
    score = fit.scores_[i]
    #print(score)
    i+=1
    if not np.isnan(float(score)):
        dictt.append([col, score])    
    else:
        removed_columns.append(col)
#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)
dictt.sort(key=lambda arr : float(arr[1]), reverse=True)

outstr = ''
i=1
for col, score in dictt:
    #if not math.isnan(float(score)):
    print('{}\t{}\t{}'.format(i, col, score))
    i+=1
    outstr += '\'' + col + '\', '


if len(removed_columns) > 0:
    print('Removed columns: {}'.format(removed_columns))

print('Columns in order from best to worst: {}'.format(outstr[:-2]))

print('The data presented in this block is bad statistics!')"""

"print('The data presented in this block is bad statistics!')\n\nselect = SelectKBest(chi2, k='all')\nfit = select.fit(X, y)\n\ndictt = []\ni=0\nremoved_columns = []\nfor col in X.columns:\n    score = fit.scores_[i]\n    #print(score)\n    i+=1\n    if not np.isnan(float(score)):\n        dictt.append([col, score])    \n    else:\n        removed_columns.append(col)\n#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)\ndictt.sort(key=lambda arr : float(arr[1]), reverse=True)\n\noutstr = ''\ni=1\nfor col, score in dictt:\n    #if not math.isnan(float(score)):\n    print('{}\t{}\t{}'.format(i, col, score))\n    i+=1\n    outstr += ''' + col + '', '\n\n\nif len(removed_columns) > 0:\n    print('Removed columns: {}'.format(removed_columns))\n\nprint('Columns in order from best to worst: {}'.format(outstr[:-2]))\n\nprint('The data presented in this block is bad statistics!')"

In [18]:
# Additions of another work found here: https://towardsdatascience.com/chi-square-test-for-feature-selection-in-machine-learning-206b1f0b8223
chi_scores = chi2(X, y)
p_values = pd.Series(chi_scores[1],index = X.columns)
p_values.sort_values(ascending = False , inplace = True)
#p_values.plot.bar()
print('Values in order of descending p-values (higher=more significant)')
print(p_values.index)

Values in order of descending p-values (higher=more significant)
Index(['avgdomaintokenlen', 'charcompvowels', 'Path_LongestWordLength',
       'sub-Directory_LongestWordLength', 'NumberRate_URL', 'dld_domain',
       'pathDomainRatio', 'Directory_LetterCount', 'isPortEighty',
       'Entropy_URL', 'ldl_domain', 'charcompace', 'avgpathtokenlen',
       'Arguments_LongestWordLength', 'spcharUrl', 'executable', 'subDirLen',
       'pathLength', 'Domain_LongestWordLength', 'SymbolCount_Afterpath',
       'URL_sensitiveWord', 'LongestPathTokenLength', 'urlLen',
       'URL_Letter_Count', 'longdomaintokenlen', 'delimeter_Domain',
       'URL_DigitCount', 'host_letter_count', 'pathurlRatio',
       'SymbolCount_Extension', 'host_DigitCount', 'SymbolCount_FileName',
       'argDomanRatio', 'delimeter_Count', 'URLQueries_variable',
       'ldl_filename', 'Directory_DigitCount', 'path_token_count',
       'Entropy_Domain', 'NumberofDotsinURL', 'domainlength',
       'Extension_LetterCount', 'Lo

In [19]:
p_values.head(10)

avgdomaintokenlen                  0.993084
charcompvowels                     0.911420
Path_LongestWordLength             0.868772
sub-Directory_LongestWordLength    0.587184
NumberRate_URL                     0.442371
dld_domain                         0.339682
pathDomainRatio                    0.305007
Directory_LetterCount              0.265838
isPortEighty                       0.248489
Entropy_URL                        0.161457
dtype: float64

In [20]:
p_values.tail(11)

Filename_LetterCount       3.891527e-33
Entropy_DirectoryName      7.487584e-36
Entropy_Filename           2.679810e-37
argPathRatio               9.901046e-38
delimeter_path             9.681864e-40
Entropy_Afterpath          3.584071e-41
SymbolCount_Domain         1.678641e-41
tld                        1.636373e-41
domain_token_count         1.636373e-41
fileNameLen                1.406341e-70
ISIpAddressInDomainName             NaN
dtype: float64