In [1]:
# Feature selection 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler

# Data management
import pandas as pd
import numpy as np

print('Imports complete.')

Imports complete.


In [2]:
# Import the data
path = './FinalDataset/'
fille = 'All.csv'
df = pd.read_csv(path + fille)

print('Data read:')
print(df.head())

Data read:
   Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...  

In [3]:
dep_var = 'URL_Type_obf_Type'

print('There are {} columns and {} rows in the provided data.'.format(len(df.columns), len(df)))

There are 80 columns and 36707 rows in the provided data.


In [4]:
print('Below is the dataset\'s composition')
print(df[dep_var].value_counts())

Below is the dataset's composition
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: URL_Type_obf_Type, dtype: int64


In [5]:
# Removes all rows if they contain NaN values
df.dropna(axis='index', inplace=True)

In [6]:
print('There are {} columns and {} rows in the provided data.'.format(len(df.columns), len(df)))

print('Below is the dataset\'s composition')
print(df[dep_var].value_counts())

There are 80 columns and 18982 rows in the provided data.
Below is the dataset's composition
spam          5342
malware       4440
phishing      4014
benign        2709
Defacement    2477
Name: URL_Type_obf_Type, dtype: int64


In [7]:
# Create the X (data) and y (labels)
#X = pd.DataFrame( normalize(df.loc[:, df.columns != dep_var]), columns=df.columns[:-1] )

scaler = MinMaxScaler()
X = pd.DataFrame( scaler.fit_transform(df.loc[:, df.columns != dep_var]), columns=df.columns[:-1] )

y = df[dep_var]

In [8]:
print(X.head())

Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0     0.000000            0.153846           0.00000           0.177083   
1     0.015884            0.153846           0.09375           0.177083   
2     0.016606            0.153846           0.09375           0.177083   
3     0.015884            0.153846           0.09375           0.177083   
4     0.016606            0.153846           0.09375           0.177083   

   longdomaintokenlen  avgpathtokenlen       tld  charcompvowels  charcompace  \
0            0.245902         0.083969  0.153846        0.020725     0.014085   
1            0.245902         0.076336  0.153846        0.098446     0.070423   
2            0.245902         0.076336  0.153846        0.098446     0.070423   
3            0.245902         0.076336  0.153846        0.098446     0.070423   
4            0.245902         0.076336  0.153846        0.098446     0.070423   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName 

In [9]:
print(y.head())

35    Defacement
37    Defacement
38    Defacement
39    Defacement
40    Defacement
Name: URL_Type_obf_Type, dtype: object


In [10]:
# Begin the feature selection process using the SelectKBest object from scikit-learn
X_new = SelectKBest(chi2, k=10).fit_transform(X, y)

In [11]:
print(X_new)

[[0.         0.         0.03871459 ... 0.         0.         0.        ]
 [0.         0.         0.4821902  ... 0.         0.54255319 0.87458339]
 [0.         0.         0.48757384 ... 0.         0.55208333 0.87413385]
 ...
 [0.08695652 0.38709677 0.75902627 ... 0.         0.51470588 0.85262228]
 [0.03381643 0.12903226 0.62794394 ... 0.         0.70909091 0.89538585]
 [0.0821256  0.19354839 0.74120529 ... 0.         0.53       0.88461893]]


## Multi-class Feature Analysis

In [12]:
select = SelectKBest(chi2, k='all')
fit = select.fit(X, y)

dictt = []
i=0
removed_columns = []
for col in X.columns:
    score = fit.scores_[i]
    #print(score)
    i+=1
    if not np.isnan(float(score)):
        dictt.append([col, score])    
    else:
        removed_columns.append(col)
#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)
dictt.sort(key=lambda arr : float(arr[1]), reverse=True)

outstr = ''
i=1
for col, score in dictt:
    #if not math.isnan(float(score)):
    print('{}\t{}\t{}'.format(i, col, score))
    i+=1
    outstr += '\'' + col + '\', '

if len(removed_columns) > 0:
    print('Removed columns: {}'.format(removed_columns))
print('Columns in order from best to worst: {}'.format(outstr[:-2]))

1	Entropy_Afterpath	1895.3587016260929
2	argPathRatio	1347.858742534321
3	NumberRate_AfterPath	1347.1581661199034
4	NumberRate_Domain	1294.3292212481244
5	ArgUrlRatio	1262.7708218689588
6	Extension_DigitCount	795.6053965093354
7	dld_getArg	687.7897203685661
8	ldl_getArg	687.5673450162649
9	Query_DigitCount	632.9948569376766
10	LongestVariableValue	631.1617676943251
11	Querylength	599.0803790960202
12	Query_LetterCount	589.495758035122
13	ldl_path	580.1595986620822
14	ArgLen	579.0924489261371
15	ldl_url	555.3217105895161
16	dld_path	534.8897872600003
17	Extension_LetterCount	525.3539856709812
18	argDomanRatio	524.5662326485201
19	dld_url	448.3967989404412
20	URL_DigitCount	436.50117151626273
21	LongestPathTokenLength	435.24924790829215
22	URLQueries_variable	432.0185878962611
23	fileNameLen	431.6027351774654
24	delimeter_Count	400.8524158795545
25	NumberRate_URL	361.45985447494013
26	SymbolCount_Domain	350.36901519499577
27	domain_token_count	350.2588688345289
28	tld	350.2588688345289
2

## Binary Class Feature Analysis

In [13]:
y = y.map(lambda label : label if label == 'benign' else 'malicious')
print(y.value_counts())

malicious    16273
benign        2709
Name: URL_Type_obf_Type, dtype: int64


In [14]:
select = SelectKBest(chi2, k='all')
fit = select.fit(X, y)

dictt = []
i=0
removed_columns = []
for col in X.columns:
    score = fit.scores_[i]
    #print(score)
    i+=1
    if not np.isnan(float(score)):
        dictt.append([col, score])    
    else:
        removed_columns.append(col)
#dictt = sorted(dictt, key=operator.itemgetter(1), reverse=True)
dictt.sort(key=lambda arr : float(arr[1]), reverse=True)

outstr = ''
i=1
for col, score in dictt:
    #if not math.isnan(float(score)):
    print('{}\t{}\t{}'.format(i, col, score))
    i+=1
    outstr += '\'' + col + '\', '


if len(removed_columns) > 0:
    print('Removed columns: {}'.format(removed_columns))

print('Columns in order from best to worst: {}'.format(outstr[:-2]))

1	fileNameLen	315.46799976653153
2	domain_token_count	182.15971387297648
3	tld	182.15971387297648
4	SymbolCount_Domain	182.10898529827438
5	Entropy_Afterpath	180.60018572738053
6	delimeter_path	174.04407653945987
7	argPathRatio	164.8426581380515
8	Entropy_Filename	162.86321472421352
9	Entropy_DirectoryName	156.24403061288692
10	Filename_LetterCount	143.819200542947
11	NumberRate_AfterPath	140.7688948111129
12	NumberRate_Extension	125.90476906341533
13	Entropy_Extension	123.26401842987504
14	ArgUrlRatio	120.95697832002074
15	NumberRate_FileName	120.04628356261605
16	dld_getArg	95.02573486132292
17	CharacterContinuityRate	92.39423328421026
18	NumberRate_DirectoryName	84.13097120620002
19	dld_filename	80.74159814413244
20	Extension_DigitCount	74.88178187241996
21	NumberRate_Domain	74.86057501029264
22	domainUrlRatio	72.36139007376572
23	dld_path	61.64997690438071
24	ldl_getArg	61.00248602175093
25	SymbolCount_URL	58.96775663519126
26	Query_DigitCount	56.01231263314264
27	dld_url	52.368454